title: ?ist? vzduch 
baseURL: https://msvehlova.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs
googleAnalytics = "UA-118022037-1"

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

